require("mackenzie.plugins-setup")
require("mackenzie.core.options")
require("mackenzie.core.keymaps")
require("mackenzie.core.colorscheme")
require("mackenzie.plugins.comment")
require("mackenzie.plugins.nvim-tree")
require("mackenzie.plugins.lualine")
require("mackenzie.plugins.telescope")
require("mackenzie.plugins.nvim-cmp")
require("mackenzie.plugins.lsp.mason")
require("mackenzie.plugins.lsp.lspsaga")
require("mackenzie.plugins.lsp.lspconfig")
require("mackenzie.plugins.lsp.null-ls")
require("mackenzie.plugins.autopairs")
require("mackenzie.plugins.treesitter")
require("mackenzie.plugins.gitsigns")
require("mackenzie.plugins.go")

